### ISSUE TITLE
Home button access denied

### ISSUE THREAD

**Issue by adamjtaylor** [jmuhlich/auto-minerva#7]
Generated stories show access denied when clicking the home button (for s3 hosted stories served through cloudfront.

Can we remove or point this back to the story "start"

**Comment by adamjtaylor** [comment]
Ino and I are also chasing this down on the portal side https://github.com/ncihtan/htan-portal/issues/324

**Comment by adamjtaylor** [comment]
Potentially remove `homeUrl`. @jmuhlich  to confirm

**Comment by jmuhlich** [comment]
minerva-browser as of v3.2.3 will not show the home button if the `homeUrl` constructor argument is omitted or falsy.
